pipeline {
    agent { node { label 'Agent-1' } }

    stages {
        stage('Init') {
            steps {
                sh '''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform plan
                '''
            }
        }
        post{
            always{
                echo "I will run always wheather the job is success or not"
            }
            success{
                echo "I will run the job if it is success"
            }
            failure{
                echo "I will not run the job if it is a failure"
            }
    }
}
